version: "3.8"

services:
  frontend:
    container_name: "frontend-server"
    build:
      context: ./frontend
    ports:
      - "5173:5173"
  
  backend:
    container_name: "backend-server"
    build:
      context: ./backend
    ports:
      - "8000:8000"
      